# This is a basic workflow to help you get started with Actions

name: Procurement

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Authentication:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Установка необходимых компонентов
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps
          pip install pytest-playwright
     
      - name: Run your tests
        run: pytest -s -v --tb=short -m auth --load-storage=auth.json
      
  SmokePassTest:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Установка необходимых компонентов
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps
          pip install pytest-playwright
          
      - name: Запуск позитивных смоук тестов
        run: pytest -s -v --tb=short -m smokepass
      - name: Discord Message Notify
        # You may pin to the exact commit or the version.
        # uses: appleboy/discord-action@4c196125180125310ac20c72034757bb71020383
        uses: appleboy/discord-action@0.0.3
        with:
          # discord webhook id
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          # discord webhook token
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          # the message contents (up to 2000 characters)
          message: |
            Tests started by 👤 ${{ github.actor }}
            From `${{ github.head_ref }}` to `${{ github.base_ref }}`
            Event `${{ github.event_name }}`
            PR ${{ github.event.number }}: ${{ github.event.push.url }}
