# This is a basic workflow to help you get started with Actions

name: Procurement

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  SmokePassTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Установка необходимых компонентов
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps
          pip install pytest-playwright
          
      - name: Запуск позитивных смоук тестов
        run: |
          pytest -s -v --tb=short -m auth
          pytest -s -v --tb=short -m smokepass
       
